# Site settings
title: Project Euler
email: wburgo999@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write ups and code for Project Euler problems
baseurl: "/Project_Euler" # the subpath of your site, e.g. /blog/
url: "http://wburgo999.github.io/Project_Euler" # the base hostname & protocol for your site
github_username:  wburgo999

# Build settings
markdown: kramdown
highlighter: pygments
kramdown:
  input: GFM
